runtime: python27
api_version: 1
threadsafe: true
service: front
handlers:
- url: /
  static_files: dist/cloud-file-check/index.html
  upload: dist/cloud-file-check/index.html
- url: /
  static_dir: dist/cloud-file-check

skip_files:
  - e2e/
  - node_modules/
  - src/
  - coverage
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.json$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.yaml$
  - ^LICENSE