runtime: python27
api_version: 1
threadsafe: true
service: front

handlers:
  - url: /(.*\.(js|map|css|png))$
    static_files: dist/cloud-file-check/\1
    upload: dist/cloud-file-check/.*\.(js|map|css|png)$

  - url: .*
    static_files: dist/cloud-file-check/index.html
    upload: dist/cloud-file-check/index.html

skip_files:
  - e2e/
  - node_modules/
  - src/
  - coverage
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.json$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.yaml$
  - ^LICENSE